const Request = {
	PROJECT_DELETE: 1,
	PROJECT_RENAME: 2,
	PROJECT_ADD: 3,
	PROJECT_CHANGE_ICO: 4,
	PROJECT_ADD_CONTIBUTOR: 5,
	PROJECT_DELETE_CONTIBUTOR: 6,

	TASK_ADD: 7,
	TASK_RENAME: 8,
	TASK_DELETE: 9,

	STEP_ADD: 10,
	STEP_RENAME: 11,
	STEP_DELETE: 12,
	STEP_TOGGLE: 13,
}

module.exports = Request